/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.CompteDAO;
import static DAO.CompteDAO.getCompte;
import DAO.ConnexionBdd;
import DAO.PompierDAO;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import modele.Compte;
import modele.Pompier;

/**
 *
 * @author ts1sio
 */
public class Frame_PompAccueil extends javax.swing.JFrame {
    
    Connection cnt;
    Pompier lePompier;

    
    private void complementGUI(){
        setIconImage(Toolkit.getDefaultToolkit()
            .getImage(getClass()
            .getResource("/img/Connexion/logo.png")));
        setTitle("APPLICATION SDIS");
    }
    
    
    /**
     * Creates new form NewJFrame
     */
    public Frame_PompAccueil() {
        initComponents();
        complementGUI();
        cnt = ConnexionBdd.ouvrirConnexion();
    }
    
     public Frame_PompAccueil(Pompier p){
        this.lePompier=p;
        initComponents();
        jlbl_prenom.setText(p.getPrenom());
        jlbl_nom.setText(p.getNom());
        jlbl_matricule.setText(p.getMatricule());
        jlbl_grade.setText(p.getLeGrade().getLibelle());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbl_logo = new javax.swing.JLabel();
        jlnomPomp = new javax.swing.JLabel();
        jlgradePomp = new javax.swing.JLabel();
        jlmatriculePomp = new javax.swing.JLabel();
        jl_prenomPomp = new javax.swing.JLabel();
        jlbl_prenom = new javax.swing.JLabel();
        jlbl_nom = new javax.swing.JLabel();
        jlbl_grade = new javax.swing.JLabel();
        jlbl_matricule = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jldecoPompier = new javax.swing.JButton();
        jbtn_infoperso = new javax.swing.JButton();
        jbtn_intervention = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(182, 85, 21));

        jlbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_appli.png"))); // NOI18N

        jlnomPomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlnomPomp.setForeground(new java.awt.Color(255, 255, 255));
        jlnomPomp.setText("Nom");

        jlgradePomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlgradePomp.setForeground(new java.awt.Color(255, 255, 255));
        jlgradePomp.setText("Grade");

        jlmatriculePomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlmatriculePomp.setForeground(new java.awt.Color(255, 255, 255));
        jlmatriculePomp.setText("Matricule");

        jl_prenomPomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_prenomPomp.setForeground(new java.awt.Color(255, 255, 255));
        jl_prenomPomp.setText("Prenom");

        jlbl_prenom.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_prenom.setText("jLabel3");

        jlbl_nom.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_nom.setText("jLabel3");

        jlbl_grade.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_grade.setText("jLabel3");

        jlbl_matricule.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_matricule.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_prenomPomp)
                                .addGap(40, 40, 40)
                                .addComponent(jlbl_prenom))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlnomPomp)
                                .addGap(63, 63, 63)
                                .addComponent(jlbl_nom))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlgradePomp)
                                .addGap(54, 54, 54)
                                .addComponent(jlbl_grade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlmatriculePomp)
                                .addGap(30, 30, 30)
                                .addComponent(jlbl_matricule))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_prenomPomp)
                    .addComponent(jlbl_prenom))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnomPomp)
                    .addComponent(jlbl_nom))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlgradePomp)
                    .addComponent(jlbl_grade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmatriculePomp)
                    .addComponent(jlbl_matricule))
                .addGap(26, 26, 26)
                .addComponent(jlbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 490));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACCUEIL POMPIER");

        jldecoPompier.setBackground(new java.awt.Color(204, 204, 204));
        jldecoPompier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jldecoPompier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Connexion/53518.png"))); // NOI18N
        jldecoPompier.setText("DECONNEXION");
        jldecoPompier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jldecoPompierActionPerformed(evt);
            }
        });

        jbtn_infoperso.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_infoperso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_infoperso.setText("Informations Personnelles ");
        jbtn_infoperso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_infopersoActionPerformed(evt);
            }
        });

        jbtn_intervention.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_intervention.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_intervention.setText("Liste des interventions");
        jbtn_intervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_interventionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtn_infoperso))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtn_intervention, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jldecoPompier, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jldecoPompier)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(jbtn_infoperso)
                .addGap(36, 36, 36)
                .addComponent(jbtn_intervention)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 520, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jldecoPompierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jldecoPompierActionPerformed
        JFrame frmInfos = new JFrame();
      frmInfos = new Frame_Connexion();
      frmInfos.setVisible(true);
      dispose();
    }//GEN-LAST:event_jldecoPompierActionPerformed

    private void jbtn_infopersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_infopersoActionPerformed
        // TODO add your handling code here:
      JFrame frmInfos = new JFrame();
      frmInfos = new Frame_PompInfoPerso(lePompier);
      frmInfos.setVisible(true);
      dispose();
        
        
    }//GEN-LAST:event_jbtn_infopersoActionPerformed

    private void jbtn_interventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_interventionActionPerformed
        // TODO add your handling code here:
          JFrame frmListe = new JFrame();
    frmListe = new Frame_ListeInterventionPompier(lePompier);
    frmListe.setVisible(true);
    dispose();   
    }//GEN-LAST:event_jbtn_interventionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_PompAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_PompAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_PompAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_PompAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_PompAccueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtn_infoperso;
    private javax.swing.JButton jbtn_intervention;
    private javax.swing.JLabel jl_prenomPomp;
    private javax.swing.JLabel jlbl_grade;
    private javax.swing.JLabel jlbl_logo;
    private javax.swing.JLabel jlbl_matricule;
    private javax.swing.JLabel jlbl_nom;
    private javax.swing.JLabel jlbl_prenom;
    private javax.swing.JButton jldecoPompier;
    private javax.swing.JLabel jlgradePomp;
    private javax.swing.JLabel jlmatriculePomp;
    private javax.swing.JLabel jlnomPomp;
    // End of variables declaration//GEN-END:variables
}
