/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JFrame;
import modele.Pompier;

/**
 *
 * @author ts1sio
 */
public class Frame_PompInfoPerso extends javax.swing.JFrame {

    Connection cnt;
    Pompier p;
    /**
     * Creates new form Frm_inforperso
     */
    public Frame_PompInfoPerso() {
        initComponents();
        complementGUI();
    }
    
    private void complementGUI(){
        setIconImage(Toolkit.getDefaultToolkit()
            .getImage(getClass()
            .getResource("/img/Connexion/logo.png")));
        setTitle("APPLICATION SDIS");
    }
    
    public Frame_PompInfoPerso(Pompier lePompier){
        initComponents();
        p=lePompier;
        jlbl_prenom.setText(p.getPrenom());
        jlbl_nom.setText(p.getNom());
        jlbl_matricule.setText(p.getMatricule());
        jlbl_grade.setText(p.getLeGrade().getLibelle());
        jlbl_dateNaissance.setText(p.getDtNaissance());
        jlbl_bip.setText(String.valueOf(p.getNumeroBip()));
        jlbl_tel.setText(p.getTelephone());
        jlbl_sexe.setText(p.getSexe());
        jlbl_caserne.setText(p.getLaCaserne().getNom());
        for(int i=0; i<p.getLesFonctions().size(); i++){
        jlcb_fonction.addItem(p.getLesFonctions().get(i).getLibelle());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jldecoPompier = new javax.swing.JButton();
        jl_prenomPomp = new javax.swing.JLabel();
        jl_nomPomp = new javax.swing.JLabel();
        jl_sexePomp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbl_prenom = new javax.swing.JLabel();
        jlbl_nom = new javax.swing.JLabel();
        jlbl_sexe = new javax.swing.JLabel();
        jlbl_dateNaissance = new javax.swing.JLabel();
        jlbl_bip = new javax.swing.JLabel();
        jlbl_tel = new javax.swing.JLabel();
        jlbl_caserne = new javax.swing.JLabel();
        jlbl_matricule = new javax.swing.JLabel();
        jlbl_grade = new javax.swing.JLabel();
        jlcb_fonction = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jlbl_logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PROFIL");

        jldecoPompier.setBackground(new java.awt.Color(204, 204, 204));
        jldecoPompier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jldecoPompier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Connexion/modifier2.png"))); // NOI18N
        jldecoPompier.setText("Retour");
        jldecoPompier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jldecoPompierActionPerformed(evt);
            }
        });

        jl_prenomPomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_prenomPomp.setForeground(new java.awt.Color(255, 255, 255));
        jl_prenomPomp.setText("Prenom");

        jl_nomPomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_nomPomp.setForeground(new java.awt.Color(255, 255, 255));
        jl_nomPomp.setText("Nom");

        jl_sexePomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_sexePomp.setForeground(new java.awt.Color(255, 255, 255));
        jl_sexePomp.setText("Sexe");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date de naissance");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numéro BIP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Téléphone");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Matricule");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Grade");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Caserne");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fonctions");

        jlbl_prenom.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_prenom.setText("jLabel3");

        jlbl_nom.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_nom.setText("jLabel3");

        jlbl_sexe.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_sexe.setText("jLabel8");

        jlbl_dateNaissance.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_dateNaissance.setText("jLabel9");

        jlbl_bip.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_bip.setText("jLabel10");

        jlbl_tel.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_tel.setText("jLabel11");

        jlbl_caserne.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_caserne.setText("jLabel14");

        jlbl_matricule.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_matricule.setText("jLabel3");

        jlbl_grade.setForeground(new java.awt.Color(255, 255, 255));
        jlbl_grade.setText("jLabel3");

        jlcb_fonction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlcb_fonctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jldecoPompier)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jl_sexePomp)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jl_prenomPomp)
                    .addComponent(jl_nomPomp))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlbl_nom)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_prenom)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlbl_caserne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbl_tel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbl_bip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbl_sexe)
                                .addComponent(jlbl_dateNaissance)
                                .addComponent(jlbl_matricule)
                                .addComponent(jlbl_grade))
                            .addComponent(jlcb_fonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jldecoPompier, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_prenomPomp)
                                            .addComponent(jlbl_prenom))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_nomPomp)
                                            .addComponent(jlbl_nom))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jl_sexePomp)
                                            .addComponent(jlbl_sexe))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1))
                                    .addComponent(jlbl_dateNaissance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(jlbl_bip))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jlbl_tel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jlbl_matricule))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(jlbl_grade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlbl_caserne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlcb_fonction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 520, 500));

        jPanel1.setBackground(new java.awt.Color(182, 85, 21));

        jlbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_appli.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jlbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 270, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xy, xx;
    private void jldecoPompierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jldecoPompierActionPerformed
        // TODO add your handling code here:
               JFrame frmInfos = new JFrame();
      frmInfos = new Frame_PompAccueil(p);
      frmInfos.setVisible(true);
      dispose();
    }//GEN-LAST:event_jldecoPompierActionPerformed

    private void jlcb_fonctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlcb_fonctionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jlcb_fonctionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_PompInfoPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_PompInfoPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_PompInfoPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_PompInfoPerso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_PompInfoPerso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jl_nomPomp;
    private javax.swing.JLabel jl_prenomPomp;
    private javax.swing.JLabel jl_sexePomp;
    private javax.swing.JLabel jlbl_bip;
    private javax.swing.JLabel jlbl_caserne;
    private javax.swing.JLabel jlbl_dateNaissance;
    private javax.swing.JLabel jlbl_grade;
    private javax.swing.JLabel jlbl_logo;
    private javax.swing.JLabel jlbl_matricule;
    private javax.swing.JLabel jlbl_nom;
    private javax.swing.JLabel jlbl_prenom;
    private javax.swing.JLabel jlbl_sexe;
    private javax.swing.JLabel jlbl_tel;
    private javax.swing.JComboBox<String> jlcb_fonction;
    private javax.swing.JButton jldecoPompier;
    // End of variables declaration//GEN-END:variables
}
