/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import DAO.CompteDAO;
import DAO.ConnexionBdd;
import DAO.PompierDAO;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modele.Compte;
import modele.Pompier;

/**
 *
 * @author ts1sio
 */
public class Frame_Connexion extends javax.swing.JFrame {
    
    Connection cnt;

    /**
     * Creates new form FrmConnexion
     */
    public Frame_Connexion() {
        initComponents();
        complementGUI();
        cnt = ConnexionBdd.ouvrirConnexion();
    }
    
    private Compte controleConnexion() throws SQLException{
        String loginSaisi = jtxt_login.getText();
        String mdpSaisi = String.valueOf(jpsw_mdp.getPassword());
        Compte unCompte = CompteDAO.getCompte(cnt, loginSaisi, mdpSaisi);
        return unCompte;
    }
    
    private void complementGUI(){
        setIconImage(Toolkit.getDefaultToolkit()
            .getImage(getClass()
            .getResource("/img/Connexion/logo.png")));
        setTitle("APPLICATION SDIS");
    }
    /**
     * Creates new form NewJFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_fond2 = new javax.swing.JPanel();
        jlbl_logo = new javax.swing.JLabel();
        jlbl_msgErreur = new javax.swing.JLabel();
        jpnl_fond1 = new javax.swing.JPanel();
        jtxt_login = new javax.swing.JTextField();
        jlbl_login = new javax.swing.JLabel();
        jlbl_mdp = new javax.swing.JLabel();
        jpsw_mdp = new javax.swing.JPasswordField();
        jlbl_connexion1 = new javax.swing.JLabel();
        jbtn_valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl_fond2.setBackground(new java.awt.Color(171, 89, 82));
        jpnl_fond2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Connexion/logo.png"))); // NOI18N
        jpnl_fond2.add(jlbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 110));
        jpnl_fond2.add(jlbl_msgErreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        getContentPane().add(jpnl_fond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 300));

        jpnl_fond1.setBackground(new java.awt.Color(233, 178, 152));
        jpnl_fond1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpnl_fond1.add(jtxt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, -1));

        jlbl_login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbl_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Connexion/utilisateur.png"))); // NOI18N
        jlbl_login.setText("Login");
        jpnl_fond1.add(jlbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jlbl_mdp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbl_mdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Connexion/key.png"))); // NOI18N
        jlbl_mdp.setText("Mot de passe");
        jpnl_fond1.add(jlbl_mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, -1));

        jpsw_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpsw_mdpActionPerformed(evt);
            }
        });
        jpnl_fond1.add(jpsw_mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, -1));

        jlbl_connexion1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlbl_connexion1.setText("CONNEXION");
        jpnl_fond1.add(jlbl_connexion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));

        jbtn_valider.setText("Valider");
        jbtn_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_validerActionPerformed(evt);
            }
        });
        jpnl_fond1.add(jbtn_valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 70, -1));

        getContentPane().add(jpnl_fond1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 200, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpsw_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpsw_mdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsw_mdpActionPerformed

    private void jbtn_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_validerActionPerformed

        try {
            // TODO add your handling code here:
            Compte leCompte = controleConnexion();
            
            JFrame leMenu = new JFrame("erreur de connexion");
            if(leCompte != null){
                int responsable = leCompte.getResponsable();
                if(responsable == 0){
                    Pompier s = PompierDAO.getPompier(cnt, leCompte.getLogin(), leCompte.getMdp());
                    leMenu = new Frame_Test(s);
                }
                leMenu.setVisible(true);
                dispose();
            }
            else
            {
                jlbl_msgErreur.setVisible(true);
                JOptionPane.showMessageDialog(null, "erreur de login et mot de passe");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jbtn_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_valider;
    private javax.swing.JLabel jlbl_connexion1;
    private javax.swing.JLabel jlbl_login;
    private javax.swing.JLabel jlbl_logo;
    private javax.swing.JLabel jlbl_mdp;
    private javax.swing.JLabel jlbl_msgErreur;
    private javax.swing.JPanel jpnl_fond1;
    private javax.swing.JPanel jpnl_fond2;
    private javax.swing.JPasswordField jpsw_mdp;
    private javax.swing.JTextField jtxt_login;
    // End of variables declaration//GEN-END:variables
}
