/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JFrame;
import modele.Pompier;
//import vue.Frame_ListePompier;

/**
 *
 * @author ts1sio
 */
public class Frm_Responsable extends javax.swing.JFrame {
    
    Pompier lePompier;

    /**
     * Creates new form Frm_Responsable
     */
    public Frm_Responsable() {
        initComponents();
        
        
    }
    public Frm_Responsable(Pompier s){
        initComponents();
        jlbl_prenomPomp.setText(s.getPrenom());
        jlbl_nomPomp.setText(s.getNom());
        jlbl_gradePomp.setText(s.getLeGrade().getLibelle());
        jlbl_matriculePomp.setText(s.getMatricule());
        
        lePompier = s;
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlnomPomp = new javax.swing.JLabel();
        jlgradePomp = new javax.swing.JLabel();
        jlmatriculePomp = new javax.swing.JLabel();
        jlpre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jldecoPompier = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlListePompier = new javax.swing.JButton();
        jlListeIntervention = new javax.swing.JButton();
        jlListeEngin = new javax.swing.JButton();
        jlListeCaserne = new javax.swing.JButton();
        jlbl_prenomPomp = new javax.swing.JLabel();
        jlbl_nomPomp = new javax.swing.JLabel();
        jlbl_gradePomp = new javax.swing.JLabel();
        jlbl_matriculePomp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(182, 85, 21));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_appli.png"))); // NOI18N

        jlnomPomp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlnomPomp.setForeground(new java.awt.Color(255, 255, 255));
        jlnomPomp.setText("Nom :");

        jlgradePomp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlgradePomp.setForeground(new java.awt.Color(255, 255, 255));
        jlgradePomp.setText("Grade :");

        jlmatriculePomp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlmatriculePomp.setForeground(new java.awt.Color(255, 255, 255));
        jlmatriculePomp.setText("Matricule :");

        jlpre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlpre.setForeground(new java.awt.Color(255, 255, 255));
        jlpre.setText("Prenom :");

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ACCUEIL RESPONSABLE ");

        jldecoPompier.setBackground(new java.awt.Color(204, 204, 204));
        jldecoPompier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jldecoPompier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Connexion/53518.png"))); // NOI18N
        jldecoPompier.setText("DECONNEXION");
        jldecoPompier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jldecoPompierActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Informations Personnelles ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlListePompier.setBackground(new java.awt.Color(204, 204, 204));
        jlListePompier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlListePompier.setText("Liste des pompiers");
        jlListePompier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlListePompierActionPerformed(evt);
            }
        });

        jlListeIntervention.setBackground(new java.awt.Color(204, 204, 204));
        jlListeIntervention.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlListeIntervention.setText("Liste des interventions");
        jlListeIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlListeInterventionActionPerformed(evt);
            }
        });

        jlListeEngin.setBackground(new java.awt.Color(204, 204, 204));
        jlListeEngin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlListeEngin.setText("Liste des engins");

        jlListeCaserne.setBackground(new java.awt.Color(204, 204, 204));
        jlListeCaserne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlListeCaserne.setText("Liste des casernes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jldecoPompier, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlListePompier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlListeIntervention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlListeEngin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlListeCaserne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addGap(0, 151, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jldecoPompier)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jlListePompier)
                .addGap(37, 37, 37)
                .addComponent(jlListeIntervention)
                .addGap(36, 36, 36)
                .addComponent(jlListeEngin)
                .addGap(38, 38, 38)
                .addComponent(jlListeCaserne)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbl_prenomPomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_prenomPomp.setForeground(new java.awt.Color(255, 255, 255));

        jlbl_nomPomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_nomPomp.setForeground(new java.awt.Color(255, 255, 255));

        jlbl_gradePomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_gradePomp.setForeground(new java.awt.Color(255, 255, 255));

        jlbl_matriculePomp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_matriculePomp.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlnomPomp)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_nomPomp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlgradePomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_gradePomp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlmatriculePomp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbl_matriculePomp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlpre)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl_prenomPomp))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlpre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_prenomPomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlnomPomp)
                    .addComponent(jlbl_nomPomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlgradePomp)
                    .addComponent(jlbl_gradePomp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlmatriculePomp)
                    .addComponent(jlbl_matriculePomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jldecoPompierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jldecoPompierActionPerformed
        JFrame frmInfos = new JFrame();
      frmInfos = new Frame_Connexion();
      frmInfos.setVisible(true);
      dispose();
        
      
            
     
     
    }//GEN-LAST:event_jldecoPompierActionPerformed

    private void jlListePompierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlListePompierActionPerformed
JFrame frmListe = new JFrame();
frmListe = new Frame_ListePompier(lePompier);
frmListe.setVisible(true);
dispose();
    }//GEN-LAST:event_jlListePompierActionPerformed

    private void jlListeInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlListeInterventionActionPerformed
JFrame frmListe = new JFrame();
frmListe = new Frame_ListeInterventionResponsable(lePompier);
frmListe.setVisible(true);
dispose();  
    }//GEN-LAST:event_jlListeInterventionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFrame frmListe = new JFrame();
    frmListe = new Frame_ResponsableInfoPerso(lePompier);
    frmListe.setVisible(true);
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    

         
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Responsable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jlListeCaserne;
    private javax.swing.JButton jlListeEngin;
    private javax.swing.JButton jlListeIntervention;
    private javax.swing.JButton jlListePompier;
    private javax.swing.JLabel jlbl_gradePomp;
    private javax.swing.JLabel jlbl_matriculePomp;
    private javax.swing.JLabel jlbl_nomPomp;
    private javax.swing.JLabel jlbl_prenomPomp;
    private javax.swing.JButton jldecoPompier;
    private javax.swing.JLabel jlgradePomp;
    private javax.swing.JLabel jlmatriculePomp;
    private javax.swing.JLabel jlnomPomp;
    private javax.swing.JLabel jlpre;
    // End of variables declaration//GEN-END:variables
}
